#my first playbook
---

- hosts: all
  become: true
  tasks:
  
  - name: update and upgrade all packages       
    dnf:
      name: '*'
      state: latest
      allow_downgrade: yes
      allowerasing: yes

  - name: install wget package
    dnf:
      name: 
        - wget
        - htop
        - zip
        - bc
        - tar  
      state: latest

         



